// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANiPMsSINWE7vMz2ZT2x0udKuc0xaPUxI',
    appId: '1:126762196030:web:97e4685ffedbe2a3f7456f',
    messagingSenderId: '126762196030',
    projectId: 'chatapp-bd4b3',
    authDomain: 'chatapp-bd4b3.firebaseapp.com',
    storageBucket: 'chatapp-bd4b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBESx1DGx3nc7J0K0M4EoFdR1nABSMpgyw',
    appId: '1:126762196030:android:ba902bfc9f0ef67af7456f',
    messagingSenderId: '126762196030',
    projectId: 'chatapp-bd4b3',
    storageBucket: 'chatapp-bd4b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDueyULZ8jaSEe0gHFXL0WeIFPOFzAo5tA',
    appId: '1:126762196030:ios:0f8b57fc0cc0cc5ff7456f',
    messagingSenderId: '126762196030',
    projectId: 'chatapp-bd4b3',
    storageBucket: 'chatapp-bd4b3.appspot.com',
    androidClientId: '126762196030-uqmei9cv62q7au2gt6ejr86csagm61eg.apps.googleusercontent.com',
    iosClientId: '126762196030-kg05tt127gt34e9ibuej7jacge80fnsv.apps.googleusercontent.com',
    iosBundleId: 'com.chatapp.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDueyULZ8jaSEe0gHFXL0WeIFPOFzAo5tA',
    appId: '1:126762196030:ios:76c146ae72610942f7456f',
    messagingSenderId: '126762196030',
    projectId: 'chatapp-bd4b3',
    storageBucket: 'chatapp-bd4b3.appspot.com',
    androidClientId: '126762196030-uqmei9cv62q7au2gt6ejr86csagm61eg.apps.googleusercontent.com',
    iosClientId: '126762196030-jiia022mrnauoct79dalh4icabf6j97k.apps.googleusercontent.com',
    iosBundleId: 'com.chatapp.chatapp.RunnerTests',
  );
}
